---
title: "maps"
format: html
---

```{r}
library(rnaturalearth)
library(rnaturalearthdata)

# Run this in your console first
# devtools::install_github("ropensci/rnaturalearthhires")
library(rnaturalearthhires)

# Plotting Maps
library(tidyverse) # Maps using ggplot() + geom_sf()
library(ggformula) # Maps using gf_sf()
library(tmap) # Thematic Maps, static and interactive
library(tmaptools)
library(tmap.mapgl)
library(osmdata) # Fetch map data from osmdata.org
library(sfheaders) # Handcrafted Map data
## Interactive Maps
library(leaflet) # interactive Maps
library(leaflet)
library(leaflet.providers)
library(leaflet.extras)
library(threejs) # Globe maps in R. Part of the htmlwidgets family of packages

# For Spatial Data Frame Processing
library(sf)
```

# https://boundingbox.klokantech.com CSV:

# 77.574028,12.917262,77.595073,12.939895

bbox_1 \<- matrix(c(77.574028, 12.917262, 77.595073, 12.939895), byrow = FALSE, nrow = 2, ncol = 2, dimnames = list(c("x", "y"), c("min", "max"))) bbox_1

77.553193,12.994856,77.582836,13.014647

```{r}
# https://boundingbox.klokantech.com CSV:
# 77.574028,12.917262,77.595073,12.939895
bbox_1 <- matrix(c(77.553193,12.994856,77.582836,13.014647), byrow = FALSE, nrow = 2,
    ncol = 2, dimnames = list(c("x", "y"), c("min", "max")))
bbox_1
```

```{r}
# Using getbb command from the osmdata package
bbox_2 <- osmdata::getbb("Malleswaram, Bangalore, India")
bbox_2
```
```{r}
road <- st_read("osm-folder/road.gpkg")
trees <- st_read("osm-folder/trees.gpkg")
building <- st_read("osm-folder/building.gpkg")
greenery <- st_read("osm-folder/greenery.gpkg")
```

 
